# [Document] https://medium.com/innovies-club/run-android-emulator-out-of-the-box-with-github-actions-b84cba766e62
# [Document] https://github.com/amrsa1/android-emulator-workflow/blob/main/start_emu_headless.sh
# [Document] https://developer.android.com/tools/releases/build-tools?hl=ko#kts
name: androidTest ì‹¤í–‰

on:
  workflow_call:

env:
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis_playstore
  API_LEVEL: 34
  ANDROID_BUILD_TOOLS_VERSION: 34.0.0
  ANDROID_SDK_PACKAGES: system-images;android-34;google_apis_playstore;x86_64 platforms;android-34 build-tools;34.0.0 platform-tools emulator
  EMULATOR_TIMEOUT: 450
  EMULATOR_NAME: nexus

jobs:
  start_androidTest:
    timeout-minutes: 50
    runs-on: macos-12
    steps:
      # [Document] https://github.com/actions/setup-java
      - name: âœ… ì½”ë“œ ì²´í¬ì•„ì›ƒ í•´ì˜¤ê¸°
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # [Document] https://github.com/actions/setup-java
      - name: â˜• JDK 17 ì„¤ì •
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # OpenJDKì˜ ê³µì‹ ë°°í¬íŒ
          cache: gradle

      # [Document] https://github.com/webfactory/ssh-agent
      - name: ðŸ” SSH Key ì„¤ì •
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add avdmanager and sdkmanager to system PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH

      - name: Install Sdk
        run: |
          yes Y | sdkmanager --licenses
          sdkmanager --install ${ANDROID_SDK_PACKAGES}

      - name: Build emulator
        run: |
          echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --abi "${ANDROID_TARGET}/${ANDROID_ARCH}" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"

      - name: Launch emulator
        run: |
          chmod +x ./.github/start_emu_headless.sh
          EMULATOR_TIMEOUT=$EMULATOR_TIMEOUT EMULATOR_NAME=$EMULATOR_NAME ./.github/start_emu_headless.sh

      - name: ðŸ§ª androidTest ì‹¤í–‰
        run: ./gradlew connectedDevDebugAndroidTest
